import { useState, type FormEvent, type ReactNode } from 'react'
import { Activity, AlertTriangle, ArrowRight, CalendarDays, Check, CheckCircle2, Circle, FileText, Flag, MessageCircle, Paperclip, Plus, Send, ShieldCheck, Sparkles, Users } from 'lucide-react'
import '../../styles/ProjectHub.css'

const people = [
  { initials: 'AJ', name: 'Alex Johnson', role: 'Product manager', color: 'blue' },
  { initials: 'SL', name: 'Sara Lee', role: 'Product designer', color: 'rose' },
  { initials: 'MC', name: 'Mark Chen', role: 'Engineering lead', color: 'green' },
  { initials: 'ER', name: 'Emily Roberts', role: 'Team member', color: 'amber' },
]

const adminUsers = [
  { name: 'Emily Roberts', email: 'emily@acme.co', initials: 'ER', color: 'amber' },
  { name: 'Michael Lee', email: 'michael@acme.co', initials: 'ML', color: 'rose' },
  { name: 'Alex Johnson', email: 'alex@acme.co', initials: 'AJ', color: 'blue' },
  { name: 'Sara Lee', email: 'sara@acme.co', initials: 'SL', color: 'green' },
]

function PagePanel({ title, subtitle, children, action }: { title: string; subtitle?: string; children: ReactNode; action?: ReactNode }) {
  return <section className="panel hub-panel"><div className="panel-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>{children}</section>
}

export function ProjectOverviewPage() {
  return <div className="hub-layout">
    <div className="hub-main-column">
      <div className="metrics-grid"><article className="metric-card"><div className="metric-top">Active projects <span className="hub-metric-icon"><FolderIcon/></span></div><div className="metric-value">08</div></article><article className="metric-card"><div className="metric-top">Team members <span className="hub-metric-icon"><Users size={14}/></span></div><div className="metric-value">26</div></article><article className="metric-card"><div className="metric-top">Total tasks <span className="hub-metric-icon"><CheckCircle2 size={14}/></span></div><div className="metric-value">120</div></article><article className="metric-card"><div className="metric-top">Overdue tasks <span className="hub-metric-icon alert"><AlertTriangle size={14}/></span></div><div className="metric-value">08</div></article></div>
      <PagePanel title="Project progress" subtitle="Completion across active projects"><div className="timeline-bars"><div className="timeline-row"><span>Website redesign</span><div className="timeline-track"><i style={{ left: '14%', width: '63%' }}/><b style={{ left: '62%', width: '24%' }}/></div><strong>78%</strong></div><div className="timeline-row"><span>Mobile app launch</span><div className="timeline-track"><i className="teal" style={{ left: '7%', width: '55%' }}/><b className="orange" style={{ left: '47%', width: '35%' }}/></div><strong>64%</strong></div><div className="timeline-row"><span>Q4 marketing</span><div className="timeline-track"><i className="purple" style={{ left: '28%', width: '38%' }}/><b className="red" style={{ left: '59%', width: '26%' }}/></div><strong>52%</strong></div></div><div className="timeline-legend"><span><i className="legend-dot"/>Completed</span><span><i className="legend-dot green"/>Planned</span><span><i className="legend-dot orange-dot"/>At risk</span></div></PagePanel>
      <div className="hub-two-column"><PagePanel title="Completion health" subtitle="Tasks completed on schedule"><div className="hub-donut-row"><div className="hub-donut"><span>76<small>%</small></span></div><div className="hub-legend"><span><i className="risk-dot green-dot"/>On track <b>6</b></span><span><i className="risk-dot amber-dot"/>Needs attention <b>2</b></span><span><i className="risk-dot red-dot"/>Behind <b>0</b></span></div></div></PagePanel><PagePanel title="Risk assessment" subtitle="Open risks requiring review"><div className="risk-list"><span><i className="risk-dot green-dot"/>High impact <b>02</b></span><span><i className="risk-dot amber-dot"/>Medium <b>04</b></span><span><i className="risk-dot red-dot"/>Low <b>01</b></span></div><button className="secondary-button">Review risks <ArrowRight size={13}/></button></PagePanel></div>
    </div>
    <aside className="hub-side-column"><PagePanel title="AI insights" subtitle="Signals from your workspace"><div className="hub-insight"><span className="insight-label"><Sparkles size={12}/> OPPORTUNITY</span><strong>Design review is ahead</strong><p>Website redesign has completed 78% of planned work, 6% ahead of schedule.</p></div><div className="hub-insight"><span className="insight-label warning"><AlertTriangle size={12}/> WATCH</span><strong>Campaign dates may move</strong><p>Two approvals are holding up the Q4 marketing launch tasks.</p></div></PagePanel><PagePanel title="Project members" subtitle="Team assigned to active work"><div className="member-list">{people.map(person=><div className="member-row" key={person.name}><span className={`person-avatar ${person.color}`}>{person.initials}</span><span className="member-name"><b>{person.name}</b><small>{person.role}</small></span><span className="member-online"/></div>)}</div><button className="secondary-button full-width"><Plus size={13}/>Add member</button></PagePanel></aside>
  </div>
}

function FolderIcon() { return <FileText size={14}/> }

export function NewProjectPage() {
  const [created, setCreated] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setCreated(true) }
  return <div className="hub-layout create-layout"><div className="hub-main-column"><PagePanel title="Project details" subtitle="Set up the essentials for your new project"><form className="project-form" onSubmit={submit}><label>Project name<input required placeholder="e.g. Website redesign"/></label><label>Description<textarea rows={3} placeholder="What is this project about?"/></label><div className="form-row"><label>Start date<input type="date" defaultValue="2026-10-07"/></label><label>Due date<input type="date"/></label></div><div className="form-row"><label>Priority<select defaultValue="Medium"><option>Low</option><option>Medium</option><option>High</option></select></label><label>Project lead<select defaultValue="Alex Johnson"><option>Alex Johnson</option><option>Sara Lee</option><option>Mark Chen</option></select></label></div><label>Team members<div className="selected-members">{people.slice(0,3).map(person=><span className="selected-person" key={person.name}><i className={`person-avatar ${person.color}`}>{person.initials}</i>{person.name}<button type="button" aria-label={`Remove ${person.name}`}>×</button></span>)}<button className="add-member-button" type="button"><Plus size={12}/>Add member</button></div></label><div className="form-actions"><span>{created ? 'Project created in demo workspace.' : 'You can update these details later.'}</span><button className="primary-button" type="submit"><Plus size={14}/>Create project</button></div></form></PagePanel></div><aside className="hub-side-column"><PagePanel title="AI project setup" subtitle="A little help getting started"><div className="ai-setup-icon"><Sparkles size={17}/></div><strong className="side-feature-title">Start with a clear plan</strong><p className="side-feature-copy">Give your project a name and goal. ProjectPulse can suggest milestones, tasks, and a timeline.</p><button className="secondary-button full-width" type="button"><Sparkles size={13}/>Suggest milestones</button></PagePanel><PagePanel title="Quick checklist"><div className="checklist"><span><Check size={12}/>Name your project</span><span><Circle size={12}/>Set a due date</span><span><Circle size={12}/>Invite collaborators</span></div></PagePanel></aside></div>
}

export function ProjectReviewPage() {
  return <div className="hub-layout"><div className="hub-main-column"><PagePanel title="Risk analysis" subtitle="Project health and delivery signals" action={<button className="select-chip">This quarter⌄</button>}><div className="risk-analysis-grid"><div className="risk-donut"><span>76<small>%</small><em>healthy</em></span></div><div className="risk-legend"><span><i className="risk-dot green-dot"/>On track <b>6</b></span><span><i className="risk-dot amber-dot"/>Needs attention <b>2</b></span><span><i className="risk-dot red-dot"/>Critical <b>1</b></span><span><i className="risk-dot purple-dot"/>Recently updated <b>4</b></span></div><div className="risk-owners"><b>High risk owners</b>{people.slice(0,3).map(person=><div className="member-row" key={person.name}><span className={`person-avatar ${person.color}`}>{person.initials}</span><span className="member-name"><b>{person.name}</b><small>2 risks · last update today</small></span><span className="risk-score">{person.name==='Alex Johnson'?'82':'64'}%</span></div>)}</div></div></PagePanel><PagePanel title="Completion rate" subtitle="Completed tasks vs weekly target"><div className="mini-bar-chart">{[55,72,61,86,74,94,79,100].map((height,index)=><div className="mini-bar-group" key={index}><i style={{height:`${height}%`}}/><b style={{height:`${Math.max(25,height-15)}%`}}/><small>{['W1','W2','W3','W4','W5','W6','W7','W8'][index]}</small></div>)}</div></PagePanel></div><aside className="hub-side-column"><PagePanel title="Risk metrics"><div className="risk-metric"><span><AlertTriangle size={14}/>Overdue tasks</span><b className="text-orange">08</b></div><div className="risk-metric"><span><Users size={14}/>Team workload</span><b className="text-teal">84%</b></div><div className="risk-metric"><span><Activity size={14}/>Project health</span><b className="text-blue">76%</b></div><div className="risk-metric"><span><CalendarDays size={14}/>Schedule risk</span><b className="text-orange">02</b></div></PagePanel><PagePanel title="Suggested actions"><div className="hub-insight"><span className="insight-label warning"><AlertTriangle size={12}/> PRIORITY</span><strong>Unblock campaign approvals</strong><p>Two overdue reviews are on the launch critical path.</p><button className="text-button">View tasks →</button></div></PagePanel></aside></div>
}

export function TeamDashboardPage() {
  const [done, setDone] = useState<string[]>(['Share sprint notes'])
  const toggle = (name: string) => setDone(current => current.includes(name) ? current.filter(item=>item!==name) : [...current,name])
  const tasks = [{name:'Review app navigation',project:'Mobile app launch',tag:'Design',color:'blue'},{name:'Prepare campaign brief',project:'Q4 marketing',tag:'Marketing',color:'orange'},{name:'Share sprint notes',project:'Website redesign',tag:'Planning',color:'green'},{name:'Confirm usability tests',project:'Website redesign',tag:'Research',color:'purple'}]
  return <div className="hub-layout"><div className="hub-main-column"><PagePanel title="My tasks" subtitle="Your work across all projects" action={<button className="filter-button">This week⌄</button>}><div className="team-task-columns">{['To do','In progress','Invitations'].map((column,index)=><div className="team-task-column" key={column}><h3>{column}<span>{index===0?'2':index===1?'2':'1'}</span></h3>{tasks.slice(index,index+2).map(task=><button className="team-task-card" key={`${column}-${task.name}`} onClick={()=>toggle(task.name)}><span className={`task-check ${done.includes(task.name)?'done':''}`}>{done.includes(task.name)&&<Check size={10}/>}</span><span><b>{task.name}</b><small>{task.project}</small></span><i className={`tag-dot ${task.color}`}/></button>)}</div>)}</div></PagePanel><div className="hub-two-column"><PagePanel title="Notifications" subtitle="Recent mentions and updates"><div className="notification-line"><span className="notification-mark"><MessageCircle size={12}/></span><span><b>Mia Chen mentioned you</b><small>“Can you review the campaign brief?”</small></span><time>12m</time></div><div className="notification-line"><span className="notification-mark success"><Check size={12}/></span><span><b>Sprint task completed</b><small>Mobile navigation flow · Sam Rivera</small></span><time>1h</time></div></PagePanel><PagePanel title="My focus"><div className="focus-line"><span>Tasks completed</span><b>8 / 12</b></div><div className="hub-progress"><i style={{width:'67%'}}/></div><div className="focus-line muted"><span>Time tracked today</span><b>4h 20m</b></div></PagePanel></div></div><aside className="hub-side-column"><PagePanel title="Team pulse" subtitle="Today’s workload"><div className="team-pulse-score"><div className="pulse-score">84<small>%</small></div><span><b>Healthy workload</b><small>Across 12 teammates</small></span></div>{people.slice(0,3).map((person,index)=><div className="workload-row" key={person.name}><span className={`person-avatar ${person.color}`}>{person.initials}</span><span>{person.name}</span><div className="hub-progress"><i style={{width:`${[72,91,61][index]}%`}}/></div></div>)}</PagePanel><PagePanel title="Team activity"><div className="activity-compact"><span className="person-avatar green">MC</span><span><b>Mia finished a task</b><small>18 minutes ago</small></span></div><div className="activity-compact"><span className="person-avatar rose">SL</span><span><b>Sara shared a design</b><small>42 minutes ago</small></span></div></PagePanel></aside></div>
}

export function TaskDetailsPage() {
  const [comments,setComments] = useState([{ name:'Mia Chen', text:'The updated layout is ready for review. I added the new mobile states.', time:'10:42 AM', initials:'MC', color:'green' },{name:'Alex Johnson',text:'Looks good. I’ll check the responsive spacing and leave notes here.',time:'11:06 AM',initials:'AJ',color:'blue'}])
  const [draft,setDraft] = useState('')
  const addComment = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!draft.trim()) return; setComments(current=>[...current,{name:'Alex Johnson',text:draft.trim(),time:'Just now',initials:'AJ',color:'blue'}]); setDraft('') }
  return <div className="hub-layout"><div className="hub-main-column"><PagePanel title="Website update" subtitle="Website redesign · TK-104" action={<span className="status-pill progress">In progress</span>}><div className="task-detail-meta"><span><CalendarDays size={13}/>Due Oct 12, 2026</span><span><Users size={13}/>Assigned to John Doe</span><span><Flag size={13}/>High priority</span></div><p className="task-description">Finalize the responsive page updates and prepare the handoff package for engineering review.</p><div className="task-detail-progress"><span>Task progress <b>65%</b></span><div className="hub-progress"><i style={{width:'65%'}}/></div></div><div className="detail-tabs"><button className="selected">Comments <span>{comments.length}</span></button><button>Activity</button><button>Subtasks <span>3</span></button><button>Attachments <span>2</span></button></div><div className="comments-heading">Comments <button className="text-button">Newest first⌄</button></div>{comments.map((comment,index)=><div className="comment-row" key={`${comment.name}-${index}`}><span className={`person-avatar ${comment.color}`}>{comment.initials}</span><div><div className="comment-meta"><b>{comment.name}</b><time>{comment.time}</time></div><p>{comment.text}</p><button className="text-button">Reply</button></div></div>)}<form className="comment-composer" onSubmit={addComment}><span className="person-avatar blue">AJ</span><input value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Write a comment..." aria-label="Write a comment"/><button className="icon-button" type="button" aria-label="Attach file"><Paperclip size={15}/></button><button className="primary-button" type="submit"><Send size={13}/>Send</button></form></PagePanel></div><aside className="hub-side-column"><PagePanel title="Task details"><div className="detail-property"><span>Status</span><b className="status-pill progress">In progress</b></div><div className="detail-property"><span>Assignee</span><b className="inline-person"><i className="person-avatar blue">JD</i>John Doe</b></div><div className="detail-property"><span>Priority</span><b className="text-orange">High</b></div><div className="detail-property"><span>Due date</span><b>Oct 12, 2026</b></div><div className="detail-property"><span>Created by</span><b>Alex Johnson</b></div></PagePanel><PagePanel title="Subtasks" subtitle="2 of 3 complete"><div className="checklist"><span><Check size={12}/>Update desktop layout</span><span><Check size={12}/>Add mobile breakpoints</span><span><Circle size={12}/>Request engineering review</span></div><button className="secondary-button full-width"><Plus size={13}/>Add subtask</button></PagePanel></aside></div>
}

export function AdminUsersPage() {
  const [roles,setRoles] = useState(['Administrator','Team member','Project manager','Team member'])
  const [active,setActive] = useState([true,true,true,false])
  const updateRole = (index:number,value:string) => setRoles(current=>current.map((role,i)=>i===index?value:role))
  const toggleActive = (index:number) => setActive(current=>current.map((enabled,i)=>i===index?!enabled:enabled))
  return <div className="hub-layout admin-layout"><div className="hub-main-column"><PagePanel title="User management" subtitle="Manage workspace access and team roles" action={<button className="filter-button">All members⌄</button>}><div className="table-scroll"><table className="data-table admin-table"><thead><tr><th>NAME</th><th>ROLE</th><th>STATUS</th><th>LAST ACTIVE</th><th /></tr></thead><tbody>{adminUsers.map((person,index)=><tr key={person.email}><td><span className="admin-person"><i className={`person-avatar ${person.color}`}>{person.initials}</i><span><b>{person.name}</b><small>{person.email}</small></span></span></td><td><select value={roles[index]} onChange={event=>updateRole(index,event.target.value)} aria-label={`Role for ${person.name}`}><option>Administrator</option><option>Project manager</option><option>Team member</option></select></td><td><button className={`status-pill ${active[index]?'':'risk'}`} onClick={()=>toggleActive(index)}>{active[index]?'Active':'Suspended'}</button></td><td>{index===0?'Now':`${index+1}h ago`}</td><td><button className="text-button">•••</button></td></tr>)}</tbody></table></div></PagePanel><PagePanel title="Permissions settings" subtitle="Default role permissions"><div className="permissions-table"><div className="permissions-row heading"><span>ROLE</span><span>VIEW</span><span>EDIT</span><span>ADMIN</span></div>{['Project manager','Team member','Administrator'].map((role,index)=><div className="permissions-row" key={role}><span><i className={`permission-swatch swatch-${index}`}/>{role}</span><span><input type="checkbox" defaultChecked/></span><span><input type="checkbox" defaultChecked={index!==1}/></span><span><input type="checkbox" defaultChecked={index===2}/></span></div>)}</div></PagePanel></div><aside className="hub-side-column"><PagePanel title="Role management" subtitle="Workspace access levels"><div className="role-card"><ShieldCheck size={15}/><span><b>Project manager</b><small>Create and manage projects</small></span></div><div className="role-card"><Users size={15}/><span><b>Team member</b><small>Collaborate on assigned work</small></span></div><div className="role-card"><ShieldCheck size={15}/><span><b>Administrator</b><small>Full workspace access</small></span></div><button className="secondary-button full-width"><Plus size={13}/>Add role</button></PagePanel><PagePanel title="Access summary"><div className="role-summary"><span>Administrators <b>2</b></span><span>Project managers <b>8</b></span><span>Team members <b>16</b></span></div></PagePanel></aside></div>
}
