import { useState } from 'react'
import { ArrowUpRight, Ellipsis, Filter, Plus, Search } from 'lucide-react'
import { ProjectStatus } from '../../components/projects/ProjectStatus'
import { getProjects } from '../../services/projectService'

const projects = getProjects()

export function ProjectsPage() {
  const [search, setSearch] = useState('')
  const visibleProjects = projects.filter(project => `${project.name} ${project.category} ${project.owner}`.toLowerCase().includes(search.toLowerCase()))
  return <div className="page-grid">
    <section className="panel"><div className="panel-heading"><div><h2>All projects <span className="heading-count">08</span></h2><p>Track active work across your workspace</p></div><button className="primary-button"><Plus size={14}/>New project</button></div><div className="table-toolbar"><button className="filter-button"><Filter size={13}/> All projects⌄</button><button className="filter-button">Status⌄</button><label className="table-search"><Search size={13}/><input aria-label="Search projects" placeholder="Search projects" value={search} onChange={event => setSearch(event.target.value)}/></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>PROJECT</th><th>OWNER</th><th>DUE DATE</th><th>PROGRESS</th><th>STATUS</th><th /></tr></thead><tbody>{visibleProjects.map(project => <tr key={project.id}><td><span className="project-cell"><i className={`project-color ${project.color}`}/><span><strong>{project.name}</strong><small>{project.id} · {project.category}</small></span></span></td><td>{project.owner}</td><td>{project.dueDate}</td><td><span className="progress-cell"><span className="progress-track"><span className="progress-fill" style={{ width: `${project.progress}%` }}/></span>{project.progress}%</span></td><td><ProjectStatus status={project.status}/></td><td><button className="icon-button" aria-label={`More actions for ${project.name}`}><Ellipsis size={16}/></button></td></tr>)}</tbody></table></div></section>
    <div className="right-stack"><article className="panel"><div className="panel-heading"><div><h2>Portfolio health</h2><p>Overall project status</p></div><button className="icon-button" aria-label="Open portfolio report"><ArrowUpRight size={15}/></button></div><div className="project-health"><div className="health-ring"><svg width="111" height="111" viewBox="0 0 100 100"><circle className="ring-track" cx="50" cy="50" r="40"/><circle className="ring-progress" cx="50" cy="50" r="40"/></svg><div className="ring-number">78%</div></div><div className="health-legend"><div><i className="status-dot"/>On track <strong>6</strong></div><div><i className="status-dot amber"/>At risk <strong>2</strong></div><div><i className="status-dot red"/>Behind <strong>0</strong></div></div></div></article><article className="panel"><div className="panel-heading"><div><h2>Recent updates</h2><p>Latest project activity</p></div></div><div className="activity-list"><div className="activity-row"><span className="avatar avatar-small">MC</span><div className="activity-copy"><strong>Website redesign updated</strong><span>18 minutes ago</span></div></div><div className="activity-row"><span className="avatar avatar-small">JL</span><div className="activity-copy"><strong>Campaign timeline changed</strong><span>1 hour ago</span></div></div><div className="activity-row"><span className="avatar avatar-small">SR</span><div className="activity-copy"><strong>Mobile app task completed</strong><span>3 hours ago</span></div></div></div></article></div>
  </div>
}