import { ArrowDownRight, ArrowUpRight, Download, TrendingUp } from 'lucide-react'
import { WeeklyBarChart } from '../../components/analytics/WeeklyBarChart'

const weeks = [
  { label: 'Aug 19', completed: 46, created: 35 }, { label: 'Aug 26', completed: 56, created: 42 }, { label: 'Sep 02', completed: 50, created: 39 }, { label: 'Sep 09', completed: 68, created: 52 }, { label: 'Sep 16', completed: 78, created: 59 }, { label: 'Sep 23', completed: 70, created: 48 }, { label: 'Sep 30', completed: 88, created: 62 }, { label: 'Oct 07', completed: 95, created: 68 },
]

export function AnalyticsPage() {
  return <>
    <section className="metrics-grid analytics-metrics"><article className="metric-card"><div className="metric-top"><span>Tasks completed</span><span className="metric-icon"><TrendingUp size={14}/></span></div><div className="metric-value">286<span className="metric-change"><ArrowUpRight size={12}/>18.4%</span></div></article><article className="metric-card"><div className="metric-top"><span>Avg. completion time</span><span className="metric-icon"><TrendingUp size={14}/></span></div><div className="metric-value">3.2d<span className="metric-change"><ArrowDownRight size={12}/>0.6 days</span></div></article><article className="metric-card"><div className="metric-top"><span>On-time delivery</span><span className="metric-icon"><TrendingUp size={14}/></span></div><div className="metric-value">92%<span className="metric-change">+4.2%</span></div></article><article className="metric-card"><div className="metric-top"><span>Team capacity</span><span className="metric-icon"><TrendingUp size={14}/></span></div><div className="metric-value">84%<span className="metric-change">Healthy</span></div></article></section>
    <div className="analytics-grid"><article className="panel"><div className="panel-heading"><div><h2>Work completed</h2><p>Tasks created and completed each week</p></div><button className="select-chip">Last 8 weeks⌄</button></div><WeeklyBarChart data={weeks}/><div className="chart-legend"><span className="legend-item"><i className="legend-dot"/>Completed</span><span className="legend-item"><i className="legend-dot green"/>Created</span></div></article><div className="right-stack"><article className="panel"><div className="panel-heading"><div><h2>Project delivery</h2><p>Progress by active project</p></div></div><div className="project-mini-list"><div className="project-mini"><i className="project-color"/><div className="project-mini-copy"><strong>Website redesign</strong><span>Due Oct 18</span></div><span className="progress-value">78%</span></div><div className="project-mini"><i className="project-color orange"/><div className="project-mini-copy"><strong>Q4 campaign</strong><span>Due Oct 24</span></div><span className="progress-value">52%</span></div><div className="project-mini"><i className="project-color green"/><div className="project-mini-copy"><strong>Mobile app launch</strong><span>Due Nov 02</span></div><span className="progress-value">64%</span></div></div></article><div className="analytics-note"><TrendingUp size={15}/><span><strong>Team velocity is trending up.</strong> Completion is 18% higher than the previous 8-week period.</span></div></div></div>
    <div className="tasks-overview"><article className="panel"><div className="panel-heading"><div><h2>Team performance</h2><p>Task completion this month</p></div><button className="icon-button" aria-label="Export report"><Download size={15}/></button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>TEAM MEMBER</th><th>COMPLETED</th><th>ON TIME</th><th>CAPACITY</th></tr></thead><tbody><tr><td>Mia Chen</td><td>32 tasks</td><td><span className="status-pill">96%</span></td><td>82%</td></tr><tr><td>Jordan Lee</td><td>28 tasks</td><td><span className="status-pill">91%</span></td><td>88%</td></tr><tr><td>Sam Rivera</td><td>25 tasks</td><td><span className="status-pill risk">84%</span></td><td>76%</td></tr></tbody></table></div></article><article className="panel"><div className="panel-heading"><div><h2>Key takeaways</h2><p>Highlights from this period</p></div></div><div className="insight-card"><span className="insight-label"><TrendingUp size={12}/> POSITIVE TREND</span><strong>Delivery is getting faster</strong><p>Average completion time dropped 0.6 days compared with the previous period.</p></div><div className="insight-card"><span className="insight-label" style={{ color: '#b67c37' }}>TEAM CAPACITY</span><strong>Room for one more initiative</strong><p>Current team utilization is healthy at 84%.</p></div></article></div>
  </>
}