import { useState } from 'react'
import { Check, Plus } from 'lucide-react'
import { PriorityTag } from '../../components/tasks/PriorityTag'
import { useTaskList } from '../../hooks/useTaskList'
import type { Task } from '../../types'

const initialTasks: Task[] = [
  { id: 'TK-104', title: 'Finalize onboarding wireframes', project: 'Website redesign', assignee: 'Mia Chen', dueDate: 'Today', priority: 'High', done: false },
  { id: 'TK-109', title: 'Review campaign landing page', project: 'Q4 marketing campaign', assignee: 'Alex Morgan', dueDate: 'Oct 09', priority: 'Medium', done: false },
  { id: 'TK-112', title: 'Share sprint notes with team', project: 'Mobile app launch', assignee: 'Sam Rivera', dueDate: 'Oct 11', priority: 'Low', done: true },
  { id: 'TK-116', title: 'Prepare usability test script', project: 'Website redesign', assignee: 'Taylor Kim', dueDate: 'Oct 12', priority: 'Medium', done: false },
  { id: 'TK-121', title: 'Confirm launch checklist', project: 'Mobile app launch', assignee: 'Sam Rivera', dueDate: 'Oct 14', priority: 'High', done: false },
]

export function TasksPage() {
  const { tasks, toggleTask } = useTaskList(initialTasks)
  const [filter, setFilter] = useState('All tasks')
  const filteredTasks = tasks.filter(task => filter === 'All tasks' || (filter === 'Completed' ? task.done : !task.done))
  return <div className="page-grid"><section className="panel"><div className="panel-heading"><div><h2>My tasks <span className="heading-count">{tasks.filter(task => !task.done).length}</span></h2><p>Keep your next actions clear and moving</p></div><button className="primary-button"><Plus size={14}/>New task</button></div><div className="table-toolbar"><select className="filter-button" value={filter} onChange={event => setFilter(event.target.value)}><option>All tasks</option><option>In progress</option><option>Completed</option></select><button className="filter-button">Due date⌄</button><button className="filter-button">Assignee⌄</button></div><div className="list-card">{filteredTasks.map(task => <div className="task-list-row" key={task.id}><button aria-label={task.done ? 'Mark task incomplete' : 'Mark task complete'} onClick={() => toggleTask(task.id)} className={`task-check ${task.done ? 'done' : ''}`}>{task.done && <Check size={11}/>}</button><div className="task-list-name"><strong className={task.done ? 'is-done' : ''}>{task.title}</strong><small>{task.id} · {task.project}</small></div><PriorityTag priority={task.priority}/><span className="task-assignee"><span className="avatar avatar-small">{task.assignee.split(' ').map(part => part[0]).join('')}</span>{task.assignee}</span><span className="task-due">{task.dueDate}</span></div>)}</div></section><aside className="right-stack"><article className="panel"><div className="panel-heading"><div><h2>Today</h2><p>Your daily focus</p></div><span className="today-date">OCT 07</span></div><div className="day-progress"><div className="day-progress-head"><strong>Daily progress</strong><span>{tasks.filter(task => task.done).length} of {tasks.length} done</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${(tasks.filter(task => task.done).length / tasks.length) * 100}%` }}/></div></div><div className="activity-list"><div className="activity-row"><span className="activity-icon"><Check size={12}/></span><div className="activity-copy"><strong>Tasks due today</strong><span>One high priority</span></div></div><div className="activity-row"><span className="activity-icon"><Check size={12}/></span><div className="activity-copy"><strong>{tasks.filter(task => task.done).length} tasks completed</strong><span>Nice work, keep it moving</span></div></div></div></article><article className="panel"><div className="panel-heading"><div><h2>By priority</h2><p>Open tasks at a glance</p></div></div><div className="priority-breakdown"><span>High <strong>{tasks.filter(task => task.priority === 'High' && !task.done).length}</strong></span><span>Medium <strong>{tasks.filter(task => task.priority === 'Medium' && !task.done).length}</strong></span><span>Low <strong>{tasks.filter(task => task.priority === 'Low' && !task.done).length}</strong></span></div></article></aside></div>
}